[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = false
evm_version = "paris"
remappings = [
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/"
]

[profile.ci]
fuzz = { runs = 100 }
invariant = { runs = 256 }


[etherscan]
  sepolia = { key = "${ETHERSCAN_API_KEY}" }

[rpc_endpoints]
  sepolia = "${RPC_URL}"